#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 08/09/2020 14:30.

# Generated by Django 3.1 on 2020-09-08 17:02

from django.db import migrations, models
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='O valor que foi pago.', max_digits=11,
                                              verbose_name='Valor')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Data do pagamento.',
                                          verbose_name='Data')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical invoice',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='O valor que foi pago.', max_digits=11,
                                              verbose_name='Valor')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Data do pagamento.',
                                          verbose_name='Data')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
