#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/09/2020 14:20.

# Generated by Django 3.1 on 2020-09-28 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='O valor que foi pago.', max_digits=11,
                                              verbose_name='Valor')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Data do pagamento.',
                                          verbose_name='Data')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('order_of_service',
                 models.OneToOneField(blank=True, help_text='Procedimento a qual esse lançamento pertence.', null=True,
                                      on_delete=django.db.models.deletion.CASCADE, to='service.orderofservice',
                                      verbose_name='Procedimento')),
                ('status',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='config.statuspayment',
                                   verbose_name='Status')),
                ('type_of_payment', models.ForeignKey(help_text='Qual foi o tipo de pagamento?', null=True,
                                                      on_delete=django.db.models.deletion.PROTECT,
                                                      to='config.typeofpayment', verbose_name='Tipo de Pagamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='O valor que foi pago.', max_digits=11,
                                              verbose_name='Valor')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Data do pagamento.',
                                          verbose_name='Data')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('order_of_service', models.ForeignKey(blank=True, db_constraint=False,
                                                       help_text='Procedimento a qual esse lançamento pertence.',
                                                       null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                       related_name='+', to='service.orderofservice',
                                                       verbose_name='Procedimento')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                             on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                             to='config.statuspayment', verbose_name='Status')),
                ('type_of_payment',
                 models.ForeignKey(blank=True, db_constraint=False, help_text='Qual foi o tipo de pagamento?',
                                   null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                   to='config.typeofpayment', verbose_name='Tipo de Pagamento')),
            ],
            options={
                'verbose_name': 'historical invoice',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
