#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 16/09/2020 16:51.

# Generated by Django 3.1 on 2020-09-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0006_auto_20200916_1639'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_of_service',
            field=models.OneToOneField(blank=True, help_text='Procedimento a qual esse lançamento pertence.', null=True,
                                       on_delete=django.db.models.deletion.CASCADE, to='service.orderofservice',
                                       verbose_name='Procedimento'),
        ),
    ]
