#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 08/09/2020 14:30.

# Generated by Django 3.1 on 2020-09-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('service', '0001_initial'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_of_service',
            field=models.ForeignKey(blank=True, help_text='Procedimento a qual esse lançamento pertence.', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='service.orderofservice',
                                    verbose_name='Procedimento'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='config.statuspayment',
                                    verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='type_of_payment',
            field=models.ForeignKey(help_text='Qual foi o tipo de pagamento?', null=True,
                                    on_delete=django.db.models.deletion.PROTECT, to='config.typeofpayment',
                                    verbose_name='Tipo de Pagamento'),
        ),
    ]
