#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 08/09/2020 14:30.

# Generated by Django 3.1 on 2020-09-08 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0002_auto_20200908_1402'),
        ('service', '0001_initial'),
        ('config', '0002_auto_20200908_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='order_of_service',
            field=models.ForeignKey(blank=True, db_constraint=False,
                                    help_text='Procedimento a qual esse lançamento pertence.', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='service.orderofservice', verbose_name='Procedimento'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='config.statuspayment', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='type_of_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Qual foi o tipo de pagamento?',
                                    null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='config.typeofpayment', verbose_name='Tipo de Pagamento'),
        ),
    ]
