#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 25/08/2020 12:31.

# Generated by Django 3.1 on 2020-08-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0006_auto_20200825_0911'),
        ('financial', '0003_auto_20200824_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='type_of_payment',
            field=models.ForeignKey(help_text='Qual foi o tipo de pagamento?', null=True,
                                    on_delete=django.db.models.deletion.PROTECT, to='config.typeofpayment',
                                    verbose_name='Tipo de Pagamento'),
        ),
    ]
