#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 24/09/2020 11:47.

# Generated by Django 3.1 on 2020-09-24 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('financial', '0003_auto_20200924_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data do pagamento.',
                                   verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data do pagamento.',
                                   verbose_name='Data'),
        ),
    ]
