#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 25/08/2020 12:31.

# Generated by Django 3.1 on 2020-08-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0007_historicalstatuspayment_statuspayment'),
        ('financial', '0004_auto_20200825_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='config.statuspayment', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='config.statuspayment',
                                    verbose_name='Status'),
        ),
    ]
