#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 14/09/2020 13:05.

# Generated by Django 3.1 on 2020-09-14 12:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardRetrieved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Pontos')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('date', models.DateField(default=datetime.datetime(2020, 9, 14, 12, 26, 58, 556461, tzinfo=utc),
                                          verbose_name='Data')),
                ('retrieved', models.BooleanField(default=False, help_text='Esse brinde já foi resgatado?',
                                                  verbose_name='Resgatado')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                               verbose_name='Cliente')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.reward',
                                             verbose_name='Brinde')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome completo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('whatsapp', models.CharField(max_length=16, verbose_name='whatsapp')),
                ('total_of_points', models.IntegerField(default=0, verbose_name='Total de pontos')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalRewardRetrieved',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Pontos')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('date', models.DateField(default=datetime.datetime(2020, 9, 14, 12, 26, 58, 556461, tzinfo=utc),
                                          verbose_name='Data')),
                ('retrieved', models.BooleanField(default=False, help_text='Esse brinde já foi resgatado?',
                                                  verbose_name='Resgatado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                               on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                               to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                             on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                             to='config.reward', verbose_name='Brinde')),
            ],
            options={
                'verbose_name': 'historical reward retrieved',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProfile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome completo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('whatsapp', models.CharField(max_length=16, verbose_name='whatsapp')),
                ('total_of_points', models.IntegerField(default=0, verbose_name='Total de pontos')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                           on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical profile',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
