#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 15/09/2020 21:50.

# Generated by Django 3.1 on 2020-09-15 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Informe uma data válida!', null=True,
                                   verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='whatsapp',
            field=models.CharField(help_text='Esse será o número usado para contato!', max_length=16,
                                   verbose_name='whatsapp'),
        ),
        migrations.AlterField(
            model_name='historicalrewardretrieved',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 15, 13, 35, 57, 984920, tzinfo=utc),
                                   verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Informe uma data válida!', null=True,
                                   verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(help_text='Esse será o número usado para contato!', max_length=16,
                                   verbose_name='whatsapp'),
        ),
        migrations.AlterField(
            model_name='rewardretrieved',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 15, 13, 35, 57, 984920, tzinfo=utc),
                                   verbose_name='Data'),
        ),
    ]
