#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 21/08/2020 14:01.

# Generated by Django 3.1 on 2020-08-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20200820_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp',
            field=models.CharField(default=6, max_length=13, verbose_name='whatsapp'),
            preserve_default=False,
        ),
    ]
