#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 24/08/2020 14:23.

# Generated by Django 3.1 on 2020-08-24 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20200821_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_of_points_not_redeemed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_of_points_redeemed',
        ),
    ]
