#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 04/09/2020 17:20.

# Generated by Django 3.1 on 2020-09-04 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_auto_20200904_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrewardretrieved',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='rewardretrieved',
            old_name='user',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='historicalrewardretrieved',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 4, 14, 3, 12, 233619, tzinfo=utc),
                                   verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='rewardretrieved',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 4, 14, 3, 12, 233619, tzinfo=utc),
                                   verbose_name='Data'),
        ),
    ]
