#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 04/09/2020 17:20.

# Generated by Django 3.1 on 2020-09-04 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0012_auto_20200904_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrewardretrieved',
            name='retrieved',
            field=models.BooleanField(default=False, help_text='Esse brinde já foi resgatado?',
                                      verbose_name='Resgatado'),
        ),
        migrations.AddField(
            model_name='rewardretrieved',
            name='retrieved',
            field=models.BooleanField(default=False, help_text='Esse brinde já foi resgatado?',
                                      verbose_name='Resgatado'),
        ),
        migrations.AlterField(
            model_name='historicalrewardretrieved',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 4, 16, 35, 56, 950112, tzinfo=utc),
                                   verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='rewardretrieved',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 4, 16, 35, 56, 950112, tzinfo=utc),
                                   verbose_name='Data'),
        ),
    ]
