#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 24/09/2020 17:36.

# Generated by Django 3.1 on 2020-09-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0015_auto_20200924_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='picture',
            field=models.TextField(default='default.png', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.png', max_length=255, upload_to='profile_pics'),
        ),
    ]
