#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/09/2020 07:44.

# Generated by Django 3.1 on 2020-09-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0016_auto_20200924_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.png', max_length=255, upload_to='profile_pics/'),
        ),
    ]
