#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/09/2020 09:22.

# Generated by Django 3.1 on 2020-09-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0017_auto_20200924_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='birth_date',
            field=models.DateField(blank=True,
                                   help_text='Dica.: No calendário clique em cima do ano no canto superior direito para mudar o ano!',
                                   null=True, verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True,
                                   help_text='Dica.: No calendário clique em cima do ano no canto superior direito para mudar o ano!',
                                   null=True, verbose_name='data de nascimento'),
        ),
    ]
