#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 08/09/2020 13:57.
TITLE_VIEW_CONFIG_TYPE_OF_PAYMENT = "Tipo de Pagamento"
TITLE_CREATE_CONFIG_TYPE_OF_PAYMENT = "Novo Tipo de Pagamento"
TITLE_EDIT_CONFIG_TYPE_OF_PAYMENT = "Editar Tipo de Pagamento"
TITLE_DEL_CONFIG_TYPE_OF_PAYMENT = "Deletar Tipo de Pagamento"
SUBTITLE_VIEW_CONFIG_TYPE_OF_PAYMENT = "Configuração de tipos de pagamentos"
# CONFIG REWARD
TITLE_VIEW_CONFIG_REWARD = "Brindes"
TITLE_CREATE_CONFIG_REWARD = "Novo Brinde"
TITLE_EDIT_CONFIG_REWARD = "Editar Brinde"
TITLE_DEL_CONFIG_REWARD = "Deletar Brinde"
SUBTITLE_VIEW_CONFIG_REWARD = "Configuração de Brindes"
# CONFIG TYPE OF SERVICE CUSTOMIZATION
TITLE_VIEW_CONFIG_TYPE_OF_SERVICE = "Tipo de Serviço"
TITLE_CREATE_CONFIG_TYPE_OF_SERVICE = "Novo Tipo de Serviço"
TITLE_EDIT_CONFIG_TYPE_OF_SERVICE = "Editar Tipo de Serviço"
TITLE_DEL_CONFIG_TYPE_OF_SERVICE = "Deletar Tipo de Serviço"
SUBTITLE_VIEW_CONFIG_TYPE_OF_SERVICE = "Configuração de tipos de serviços"
# CONFIG STATUS SERVICE CUSTOMIZATION
TITLE_VIEW_CONFIG_STATUS_SERVICE = "Status do Serviço"
TITLE_CREATE_CONFIG_STATUS_SERVICE = "Novo Status do Serviço"
TITLE_EDIT_CONFIG_STATUS_SERVICE = "Editar Status do Serviço"
TITLE_DEL_CONFIG_STATUS_SERVICE = "Deletar Status do Serviço"
SUBTITLE_VIEW_CONFIG_STATUS_SERVICE = "Configuração de status de serviço"
# CONFIG STATUS PAYMENT CUSTOMIZATION
TITLE_VIEW_CONFIG_STATUS_PAYMENT = "Status de Pagamento"
TITLE_CREATE_CONFIG_STATUS_PAYMENT = "Novo Status de Pagamento"
TITLE_EDIT_CONFIG_STATUS_PAYMENT = "Editar Status de Pagamento"
TITLE_DEL_CONFIG_STATUS_PAYMENT = "Deletar Status de Pagamento"
SUBTITLE_VIEW_CONFIG_STATUS_PAYMENT = "Configuração de status de pagamento"
# CONFIG EXPEDIENT
TITLE_VIEW_CONFIG_EXPEDIENT = "Expediente"
TITLE_CREATE_CONFIG_EXPEDIENT = "Novo Expedient"
TITLE_EDIT_CONFIG_EXPEDIENT = "Editar Expediente"
TITLE_DEL_CONFIG_EXPEDIENT = "Deletar Expediente"
SUBTITLE_VIEW_CONFIG_EXPEDIENT = "Configuração de expediente"
