#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 21/09/2020 21:42.

# Generated by Django 3.1 on 2020-09-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsmessages',
            name='show',
        ),
        migrations.AddField(
            model_name='notificationsmessages',
            name='isreaded',
            field=models.BooleanField(default=False),
        ),
    ]
