#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 21/09/2020 21:42.

# Generated by Django 3.1 on 2020-09-21 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0002_auto_20200921_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationsMessages',
        ),
    ]
