#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 08/11/2020 11:16.

# Generated by Django 3.1 on 2020-11-08 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhomepage',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.DeleteModel(
            name='HistoricalHomePage',
        ),
    ]
