#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 21/09/2020 21:42.

# Generated by Django 3.1 on 2020-09-21 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsite',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.DeleteModel(
            name='HistoricalSite',
        ),
    ]
