#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 18/08/2020 16:42.

# Generated by Django 3.1 on 2020-08-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0002_auto_20200818_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltypeofservice',
            name='rewarded_points',
            field=models.FloatField(default=0, verbose_name='pontos ganhos'),
        ),
        migrations.AddField(
            model_name='typeofservice',
            name='rewarded_points',
            field=models.FloatField(default=0, verbose_name='pontos ganhos'),
        ),
    ]
