#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 23/09/2020 10:54.

# Generated by Django 3.1 on 2020-09-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0003_historicalhomepage_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhomepage',
            name='email',
            field=models.EmailField(blank=True, help_text='Opcional!', max_length=254, null=True,
                                    verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.EmailField(blank=True, help_text='Opcional!', max_length=254, null=True,
                                    verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='historicalhomepage',
            name='address',
            field=models.CharField(help_text='Sugestão: Rua, Número, Cidade - Estado, CEP', max_length=255,
                                   verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='address',
            field=models.CharField(help_text='Sugestão: Rua, Número, Cidade - Estado, CEP', max_length=255,
                                   verbose_name='Endereço Completo'),
        ),
    ]
