#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 24/08/2020 13:18.

# Generated by Django 3.1 on 2020-08-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0003_historicaltypeofpayment_typeofpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltypeofservice',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0,
                                      help_text='Valor do procedimento, ele será usado para auto preenchimento de alguns campos!',
                                      max_digits=11, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='typeofservice',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0,
                                      help_text='Valor do procedimento, ele será usado para auto preenchimento de alguns campos!',
                                      max_digits=11, verbose_name='Valor'),
        ),
    ]
