#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/09/2020 09:22.

# Generated by Django 3.1 on 2020-09-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0004_auto_20200923_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhomepage',
            name='first_image',
            field=models.TextField(blank=True, help_text='Imagem que fica no início da página.', max_length=100,
                                   null=True, verbose_name='Primeira Imagem'),
        ),
        migrations.AddField(
            model_name='historicalhomepage',
            name='first_video_url',
            field=models.CharField(blank=True, help_text='URL do primeiro vídeo, fica no início da página',
                                   max_length=255, null=True, verbose_name='Primeiro Video'),
        ),
        migrations.AddField(
            model_name='historicalhomepage',
            name='second_video_url',
            field=models.CharField(blank=True, help_text='URL do segundo vídeo, fica na primeira página de sobre',
                                   max_length=255, null=True, verbose_name='Segundo Video'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_image',
            field=models.ImageField(blank=True, help_text='Imagem que fica no início da página.', null=True,
                                    upload_to='homepage/', verbose_name='Primeira Imagem'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_video_url',
            field=models.CharField(blank=True, help_text='URL do primeiro vídeo, fica no início da página',
                                   max_length=255, null=True, verbose_name='Primeiro Video'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_video_url',
            field=models.CharField(blank=True, help_text='URL do segundo vídeo, fica na primeira página de sobre',
                                   max_length=255, null=True, verbose_name='Segundo Video'),
        ),
    ]
