#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 25/08/2020 09:32.

# Generated by Django 3.1 on 2020-08-25 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0004_auto_20200824_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltypeofservice',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Quanto tempo leva esse procedimento?',
                                   verbose_name='tempo'),
        ),
        migrations.AddField(
            model_name='typeofservice',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Quanto tempo leva esse procedimento?',
                                   verbose_name='tempo'),
        ),
    ]
