#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 25/08/2020 09:32.

# Generated by Django 3.1 on 2020-08-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0005_auto_20200825_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltypeofservice',
            name='time',
            field=models.FloatField(default=30, help_text='Coloque o tempo em minutos, ex.: 1hr = 60min',
                                    verbose_name='tempo'),
        ),
        migrations.AlterField(
            model_name='typeofservice',
            name='time',
            field=models.FloatField(default=30, help_text='Coloque o tempo em minutos, ex.: 1hr = 60min',
                                    verbose_name='tempo'),
        ),
    ]
