#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/09/2020 09:22.

# Generated by Django 3.1 on 2020-09-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0005_auto_20200928_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhomepage',
            name='second_image',
            field=models.TextField(blank=True, help_text='Imagem que fica na parte sobre como plano de fundo do video.',
                                   max_length=100, null=True, verbose_name='Segunda Imagem'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_image',
            field=models.ImageField(blank=True,
                                    help_text='Imagem que fica na parte sobre como plano de fundo do video.', null=True,
                                    upload_to='homepage/', verbose_name='Segunda Imagem'),
        ),
    ]
