#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 25/08/2020 12:31.

# Generated by Django 3.1 on 2020-08-25 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0006_auto_20200825_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('contextual', models.CharField(blank=True,
                                                choices=[('success', 'VERDE'), ('primary', 'AZUL'), ('info', 'CIANO'),
                                                         ('warning', 'AMARELO'), ('danger', 'VERMELHO'),
                                                         ('default', 'CINZA')], max_length=20, verbose_name='cor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalStatusPayment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('contextual', models.CharField(blank=True,
                                                choices=[('success', 'VERDE'), ('primary', 'AZUL'), ('info', 'CIANO'),
                                                         ('warning', 'AMARELO'), ('danger', 'VERMELHO'),
                                                         ('default', 'CINZA')], max_length=20, verbose_name='cor')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical status payment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
