#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 27/08/2020 17:24.

# Generated by Django 3.1 on 2020-08-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0007_historicalstatuspayment_statuspayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltypeofservice',
            name='color',
            field=models.CharField(default='#ffffff', help_text='Cor em hexadecimal, ex.: #ffffff para branco',
                                   max_length=7, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='typeofservice',
            name='color',
            field=models.CharField(default='#ffffff', help_text='Cor em hexadecimal, ex.: #ffffff para branco',
                                   max_length=7, verbose_name='cor'),
        ),
    ]
