#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 27/08/2020 17:24.

# Generated by Django 3.1 on 2020-08-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0008_auto_20200827_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltypeofservice',
            name='color',
        ),
        migrations.RemoveField(
            model_name='typeofservice',
            name='color',
        ),
        migrations.AddField(
            model_name='historicaltypeofservice',
            name='contextutal',
            field=models.CharField(default='#ffffff', help_text='Escolha uma cor para representar esse procedimento!',
                                   max_length=7, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='typeofservice',
            name='contextutal',
            field=models.CharField(default='#ffffff', help_text='Escolha uma cor para representar esse procedimento!',
                                   max_length=7, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='historicalstatuspayment',
            name='contextual',
            field=models.CharField(default='#ffffff', help_text='Escolha uma cor para representar esse status',
                                   max_length=7, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='historicalstatusservice',
            name='contextual',
            field=models.CharField(default='#ffffff', help_text='Escolha uma cor para representar esse status',
                                   max_length=7, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='statuspayment',
            name='contextual',
            field=models.CharField(default='#ffffff', help_text='Escolha uma cor para representar esse status',
                                   max_length=7, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='statusservice',
            name='contextual',
            field=models.CharField(default='#ffffff', help_text='Escolha uma cor para representar esse status',
                                   max_length=7, verbose_name='cor'),
        ),
    ]
