#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 02/09/2020 19:50.

# Generated by Django 3.1 on 2020-09-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0010_auto_20200827_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltypeofservice',
            name='rewarded_points',
            field=models.IntegerField(default=0, verbose_name='pontos ganhos'),
        ),
        migrations.AlterField(
            model_name='typeofservice',
            name='rewarded_points',
            field=models.IntegerField(default=0, verbose_name='pontos ganhos'),
        ),
    ]
