#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 04/09/2020 17:20.

# Generated by Django 3.1 on 2020-09-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0011_auto_20200902_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreward',
            name='contextual',
            field=models.CharField(default='#ffffff', help_text='Escolha uma cor para representar esse brinde!',
                                   max_length=7, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='reward',
            name='contextual',
            field=models.CharField(default='#ffffff', help_text='Escolha uma cor para representar esse brinde!',
                                   max_length=7, verbose_name='cor'),
        ),
    ]
