#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 04/09/2020 17:20.

# Generated by Django 3.1 on 2020-09-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0013_auto_20200904_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreward',
            name='description',
            field=models.TextField(default='blablba lba lbalbalbal', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='description',
            field=models.TextField(default='blablablal ablalblalb', verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
