#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 04/09/2020 17:20.

# Generated by Django 3.1 on 2020-09-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0014_auto_20200904_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreward',
            name='image',
            field=models.TextField(blank=True, help_text='Foto representando o brinde.', max_length=100, null=True,
                                   verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.FileField(blank=True, help_text='Foto representando o brinde.', null=True, upload_to='',
                                   verbose_name='Foto'),
        ),
    ]
