#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 04/09/2020 17:20.

# Generated by Django 3.1 on 2020-09-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0015_auto_20200904_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreward',
            name='quantity_in_points',
            field=models.IntegerField(default=1, verbose_name='quantidade de pontos'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='quantity_in_points',
            field=models.IntegerField(default=1, verbose_name='quantidade de pontos'),
        ),
    ]
