#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 06/09/2020 11:06.

# Generated by Django 3.1 on 2020-09-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0016_auto_20200904_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltypeofservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='typeofservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='historicalreward',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
