#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 06/09/2020 11:06.

# Generated by Django 3.1 on 2020-09-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0017_auto_20200905_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltypeofservice',
            name='image',
            field=models.TextField(blank=True, help_text='Foto representando o procedimento.', max_length=100,
                                   null=True, verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='typeofservice',
            name='image',
            field=models.FileField(blank=True, help_text='Foto representando o procedimento.', null=True, upload_to='',
                                   verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='historicalreward',
            name='description',
            field=models.TextField(blank=True, help_text='Usado no site para descrever o brinde',
                                   verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='historicaltypeofservice',
            name='description',
            field=models.TextField(blank=True, help_text='Usado no site para descrever o procedimento',
                                   verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, help_text='Usado no site para descrever o brinde',
                                   verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='typeofservice',
            name='description',
            field=models.TextField(blank=True, help_text='Usado no site para descrever o procedimento',
                                   verbose_name='Descrição'),
        ),
    ]
