#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 08/09/2020 14:30.

# Generated by Django 3.1 on 2020-09-08 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime(2020, 9, 8, 17, 2, 6, 749138, tzinfo=utc),
                                         help_text='Caso selecionado vários dias, deixe como está!',
                                         verbose_name='dia')),
                ('color',
                 models.CharField(default='#D40CD4', help_text='Qual a cor que você deseja como plano de fundo',
                                  max_length=7, verbose_name='cor')),
                ('is_work_day', models.BooleanField(default=True, help_text='Esse dia estará trabalhando?',
                                                    verbose_name='dia de trabalho')),
                ('force_day_full',
                 models.BooleanField(default=False, help_text='Forçar para que o dia mostre como lotado!',
                                     verbose_name='forçar dia cheio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalBusinessDay',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime(2020, 9, 8, 17, 2, 6, 749138, tzinfo=utc),
                                         help_text='Caso selecionado vários dias, deixe como está!',
                                         verbose_name='dia')),
                ('color',
                 models.CharField(default='#D40CD4', help_text='Qual a cor que você deseja como plano de fundo',
                                  max_length=7, verbose_name='cor')),
                ('is_work_day', models.BooleanField(default=True, help_text='Esse dia estará trabalhando?',
                                                    verbose_name='dia de trabalho')),
                ('force_day_full',
                 models.BooleanField(default=False, help_text='Forçar para que o dia mostre como lotado!',
                                     verbose_name='forçar dia cheio')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical business day',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
