#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 14/09/2020 13:05.

# Generated by Django 3.1 on 2020-09-14 12:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBusinessDay',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime(2020, 9, 14, 12, 26, 58, 579648, tzinfo=utc),
                                         help_text='Caso selecionado vários dias, deixe como está!',
                                         verbose_name='dia')),
                ('color',
                 models.CharField(default='#D40CD4', help_text='Qual a cor que você deseja como plano de fundo',
                                  max_length=7, verbose_name='cor')),
                ('is_work_day', models.BooleanField(default=True, help_text='Esse dia estará trabalhando?',
                                                    verbose_name='dia de trabalho')),
                ('force_day_full',
                 models.BooleanField(default=False, help_text='Forçar para que o dia mostre como lotado!',
                                     verbose_name='forçar dia cheio')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical business day',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BusinessDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime(2020, 9, 14, 12, 26, 58, 579648, tzinfo=utc),
                                         help_text='Caso selecionado vários dias, deixe como está!',
                                         verbose_name='dia')),
                ('color',
                 models.CharField(default='#D40CD4', help_text='Qual a cor que você deseja como plano de fundo',
                                  max_length=7, verbose_name='cor')),
                ('is_work_day', models.BooleanField(default=True, help_text='Esse dia estará trabalhando?',
                                                    verbose_name='dia de trabalho')),
                ('force_day_full',
                 models.BooleanField(default=False, help_text='Forçar para que o dia mostre como lotado!',
                                     verbose_name='forçar dia cheio')),
                ('expedient_day', models.ManyToManyField(help_text='Quais são os horários disponíveis para esse dia?',
                                                         to='config.Expedient', verbose_name='Expediente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
