#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 15/09/2020 21:50.

# Generated by Django 3.1 on 2020-09-15 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 9, 15, 13, 35, 58, 10257, tzinfo=utc),
                                   help_text='Caso selecionado vários dias, deixe como está!', verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='historicalbusinessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 9, 15, 13, 35, 58, 10257, tzinfo=utc),
                                   help_text='Caso selecionado vários dias, deixe como está!', verbose_name='dia'),
        ),
    ]
