#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 16/09/2020 16:51.

# Generated by Django 3.1 on 2020-09-16 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('worker', '0003_auto_20200916_0951'),
        ('business', '0004_auto_20200916_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessday',
            name='workers',
            field=models.ManyToManyField(blank=True, help_text='Quais funcionários estão trabalhando nesse dia?',
                                         to='worker.WorkerProfile', verbose_name='Funcionários'),
        ),
        migrations.AlterField(
            model_name='businessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 9, 16, 17, 27, 22, 31335, tzinfo=utc),
                                   help_text='Caso selecionado vários dias, deixe como está!', verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='historicalbusinessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 9, 16, 17, 27, 22, 31335, tzinfo=utc),
                                   help_text='Caso selecionado vários dias, deixe como está!', verbose_name='dia'),
        ),
    ]
