#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/08/2020 12:32.

# Generated by Django 3.1 on 2020-08-27 20:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0004_auto_20200827_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessday',
            name='color',
            field=models.CharField(default='#ffddff', max_length=7, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='historicalbusinessday',
            name='color',
            field=models.CharField(default='#ffddff', max_length=7, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='businessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 8, 27, 20, 29, 19, 30302, tzinfo=utc),
                                   verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='historicalbusinessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 8, 27, 20, 29, 19, 30302, tzinfo=utc),
                                   verbose_name='dia'),
        ),
    ]
