#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/08/2020 18:14.

# Generated by Django 3.1 on 2020-08-28 16:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0005_auto_20200827_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessday',
            name='force_day_full',
            field=models.BooleanField(default=False,
                                      help_text='Forçar que o dia não esteja disponível, mostrando como lotado!',
                                      verbose_name='forçar dia cheio'),
        ),
        migrations.AddField(
            model_name='historicalbusinessday',
            name='force_day_full',
            field=models.BooleanField(default=False,
                                      help_text='Forçar que o dia não esteja disponível, mostrando como lotado!',
                                      verbose_name='forçar dia cheio'),
        ),
        migrations.AlterField(
            model_name='businessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 16, 6, 46, 162679, tzinfo=utc),
                                   verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='historicalbusinessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 16, 6, 46, 162679, tzinfo=utc),
                                   verbose_name='dia'),
        ),
    ]
