#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/08/2020 18:14.

# Generated by Django 3.1 on 2020-08-28 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0006_auto_20200828_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessday',
            name='color',
            field=models.CharField(default='#ffddff', help_text='Qual a cor que você deseja como plano de fundo',
                                   max_length=7, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='businessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 18, 6, 26, 730854, tzinfo=utc),
                                   help_text='Caso selecionado vários dias, deixe como está!', verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='businessday',
            name='expedient_day',
            field=models.ManyToManyField(blank=True, help_text='Quais são os horários disponíveis para esse dia?',
                                         to='business.Expedient', verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='businessday',
            name='is_work_day',
            field=models.BooleanField(default=True, help_text='Esse dia estará trabalhando?',
                                      verbose_name='dia de trabalho'),
        ),
        migrations.AlterField(
            model_name='historicalbusinessday',
            name='color',
            field=models.CharField(default='#ffddff', help_text='Qual a cor que você deseja como plano de fundo',
                                   max_length=7, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='historicalbusinessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 18, 6, 26, 730854, tzinfo=utc),
                                   help_text='Caso selecionado vários dias, deixe como está!', verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='historicalbusinessday',
            name='is_work_day',
            field=models.BooleanField(default=True, help_text='Esse dia estará trabalhando?',
                                      verbose_name='dia de trabalho'),
        ),
    ]
