#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/08/2020 18:14.

# Generated by Django 3.1 on 2020-08-28 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0007_auto_20200828_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 18, 8, 40, 347042, tzinfo=utc),
                                   help_text='Caso selecionado vários dias, deixe como está!', verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='businessday',
            name='expedient_day',
            field=models.ManyToManyField(help_text='Quais são os horários disponíveis para esse dia?',
                                         to='business.Expedient', verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='historicalbusinessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 18, 8, 40, 347042, tzinfo=utc),
                                   help_text='Caso selecionado vários dias, deixe como está!', verbose_name='dia'),
        ),
    ]
