#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 02/09/2020 19:50.

# Generated by Django 3.1 on 2020-09-02 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0008_auto_20200828_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessday',
            name='color',
            field=models.CharField(default='#D40CD4', help_text='Qual a cor que você deseja como plano de fundo',
                                   max_length=7, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='businessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 16, 30, 25, 914551, tzinfo=utc),
                                   help_text='Caso selecionado vários dias, deixe como está!', verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='businessday',
            name='force_day_full',
            field=models.BooleanField(default=False, help_text='Forçar para que o dia mostre como lotado!',
                                      verbose_name='forçar dia cheio'),
        ),
        migrations.AlterField(
            model_name='historicalbusinessday',
            name='color',
            field=models.CharField(default='#D40CD4', help_text='Qual a cor que você deseja como plano de fundo',
                                   max_length=7, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='historicalbusinessday',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 16, 30, 25, 914551, tzinfo=utc),
                                   help_text='Caso selecionado vários dias, deixe como está!', verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='historicalbusinessday',
            name='force_day_full',
            field=models.BooleanField(default=False, help_text='Forçar para que o dia mostre como lotado!',
                                      verbose_name='forçar dia cheio'),
        ),
    ]
