#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 16/09/2020 10:03.

# Generated by Django 3.1 on 2020-09-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0002_historicalsite_site'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkerprofile',
            old_name='customuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workerprofile',
            old_name='customuser',
            new_name='user',
        ),
        migrations.AddField(
            model_name='historicalworkerprofile',
            name='name',
            field=models.CharField(default='func', max_length=150, verbose_name='nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='name',
            field=models.CharField(default='func', max_length=150, verbose_name='nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='expertise',
            field=models.ManyToManyField(blank=True, help_text='Quais procedimentos esse funcionário é especializado?',
                                         to='config.TypeOfService', verbose_name='Especialidades'),
        ),
    ]
