#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 13/09/2020 13:12.

# Generated by Django 3.1 on 2020-09-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0002_auto_20200908_1402'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='expertise',
            field=models.ManyToManyField(blank=True, help_text='Quais procedimentos esse funcionário é capaz de fazer?',
                                         to='config.TypeOfService', verbose_name='Especialidades'),
        ),
    ]
