#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 16/09/2020 10:03.

# Generated by Django 3.1 on 2020-09-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('worker', '0002_auto_20200916_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkerprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Informe uma data válida!', null=True,
                                   verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='historicalworkerprofile',
            name='whatsapp',
            field=models.CharField(default='66', help_text='Esse será o número usado para contato!', max_length=16,
                                   verbose_name='whatsapp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Informe uma data válida!', null=True,
                                   verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='whatsapp',
            field=models.CharField(default='66', help_text='Esse será o número usado para contato!', max_length=16,
                                   verbose_name='whatsapp'),
            preserve_default=False,
        ),
    ]
