#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/09/2020 14:20.

# Generated by Django 3.1 on 2020-09-28 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False, verbose_name='finalizado')),
                ('counted', models.BooleanField(default=False, help_text='Procedimento já foi contabilizado?',
                                                verbose_name='contabilizado')),
                ('confirmed', models.BooleanField(default=False, help_text='Procedimento foi confirmado?',
                                                  verbose_name='confirmado')),
                ('canceled',
                 models.BooleanField(default=False, help_text='Procedimento foi cancelado?', verbose_name='cancelado')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora')),
                ('observation', models.TextField(blank=True, verbose_name='observação')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.statusservice',
                                             verbose_name='Status')),
                ('type_of_service',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.typeofservice',
                                   verbose_name='Procedimento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrderOfService',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('finished', models.BooleanField(default=False, verbose_name='finalizado')),
                ('counted', models.BooleanField(default=False, help_text='Procedimento já foi contabilizado?',
                                                verbose_name='contabilizado')),
                ('confirmed', models.BooleanField(default=False, help_text='Procedimento foi confirmado?',
                                                  verbose_name='confirmado')),
                ('canceled',
                 models.BooleanField(default=False, help_text='Procedimento foi cancelado?', verbose_name='cancelado')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora')),
                ('observation', models.TextField(blank=True, verbose_name='observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                               on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                               to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                             on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                             to='config.statusservice', verbose_name='Status')),
                ('type_of_service', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                      on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                      to='config.typeofservice', verbose_name='Procedimento')),
            ],
            options={
                'verbose_name': 'historical order of service',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
