#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 21/08/2020 17:26.

# Generated by Django 3.1 on 2020-08-21 18:17

import datetime
from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrderOfService',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('finished',
                 models.BooleanField(default=False, help_text='Marque apenas quando procedimento finalizado',
                                     verbose_name='finalizado')),
                ('counted', models.BooleanField(default=False, help_text='Procedimento já foi contabilizado?',
                                                verbose_name='contabilizado')),
                ('confirmed', models.BooleanField(default=False, help_text='Procedimento foi confirmado?',
                                                  verbose_name='confirmado')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Data')),
                ('time', models.TimeField(default=datetime.datetime.now, verbose_name='Hora')),
                ('observation', models.TextField(blank=True, verbose_name='observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical order of service',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrderOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished',
                 models.BooleanField(default=False, help_text='Marque apenas quando procedimento finalizado',
                                     verbose_name='finalizado')),
                ('counted', models.BooleanField(default=False, help_text='Procedimento já foi contabilizado?',
                                                verbose_name='contabilizado')),
                ('confirmed', models.BooleanField(default=False, help_text='Procedimento foi confirmado?',
                                                  verbose_name='confirmado')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Data')),
                ('time', models.TimeField(default=datetime.datetime.now, verbose_name='Hora')),
                ('observation', models.TextField(blank=True, verbose_name='observação')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
