#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 21/08/2020 13:38.

# Generated by Django 3.1 on 2020-08-19 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrderOfService',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('finished',
                 models.BooleanField(default=False, help_text='Marque apenas quando procedimento finalizado',
                                     verbose_name='finalizado')),
                ('counted', models.BooleanField(default=False, help_text='Procedimento já foi contabilizado?',
                                                verbose_name='contabilizado')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data e Hora')),
                ('observation', models.TextField(blank=True, verbose_name='observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical order of service',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrderOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished',
                 models.BooleanField(default=False, help_text='Marque apenas quando procedimento finalizado',
                                     verbose_name='finalizado')),
                ('counted', models.BooleanField(default=False, help_text='Procedimento já foi contabilizado?',
                                                verbose_name='contabilizado')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data e Hora')),
                ('observation', models.TextField(blank=True, verbose_name='observação')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.statusservice',
                                             verbose_name='Status')),
                ('type_of_service',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.typeofservice',
                                   verbose_name='Procedimento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
