#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 08/09/2020 14:30.

# Generated by Django 3.1 on 2020-09-08 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
        ('config', '0002_auto_20200908_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderofservice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='orderofservice',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.statusservice',
                                    verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='orderofservice',
            name='type_of_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.typeofservice',
                                    verbose_name='Procedimento'),
        ),
        migrations.AddField(
            model_name='historicalorderofservice',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historicalorderofservice',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorderofservice',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='config.statusservice', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='historicalorderofservice',
            name='type_of_service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='config.typeofservice', verbose_name='Procedimento'),
        ),
    ]
