#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 21/08/2020 14:01.

# Generated by Django 3.1 on 2020-08-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0002_auto_20200819_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderofservice',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Procedimento foi confirmado?',
                                      verbose_name='confirmado'),
        ),
        migrations.AddField(
            model_name='orderofservice',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Procedimento foi confirmado?',
                                      verbose_name='confirmado'),
        ),
    ]
