#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 21/08/2020 14:01.

# Generated by Django 3.1 on 2020-08-21 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0003_auto_20200821_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderofservice',
            name='time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='orderofservice',
            name='time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='historicalorderofservice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Data'),
        ),
    ]
