#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 21/08/2020 14:01.

# Generated by Django 3.1 on 2020-08-21 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0007_auto_20200821_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorderofservice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderofservice',
            name='status',
        ),
    ]
