#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 07/09/2020 17:37.

# Generated by Django 3.1 on 2020-09-07 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0032_auto_20200907_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderofservice',
            name='canceled',
            field=models.BooleanField(default=False, help_text='Procedimento foi cancelado?', verbose_name='cancelado'),
        ),
        migrations.AddField(
            model_name='orderofservice',
            name='canceled',
            field=models.BooleanField(default=False, help_text='Procedimento foi cancelado?', verbose_name='cancelado'),
        ),
        migrations.AlterField(
            model_name='historicalorderofservice',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 7, 16, 12, 57, 656996, tzinfo=utc),
                                   verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='historicalorderofservice',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 7, 16, 12, 57, 657164, tzinfo=utc),
                                   verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 7, 16, 12, 57, 656996, tzinfo=utc),
                                   verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 7, 16, 12, 57, 657164, tzinfo=utc),
                                   verbose_name='Hora'),
        ),
    ]
